dist: xenial   # required for Python >= 3.7
language: python
python:
  - "3.7"

install: 
   pip3 install --upgrade pip 
script: 
 pytest -s -q
notifications:
  webhooks:
    - https://crowdbotic-test.herokuapp.com/api/v1/challenge/check_builds/
